package com.kerjalah.app.data

import android.util.Log
import io.github.jan.supabase.postgrest.from
import io.github.jan.supabase.realtime.PostgresAction
import io.github.jan.supabase.realtime.channel
import io.github.jan.supabase.realtime.postgresChangeFlow
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.launchIn
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.onEach
import kotlinx.coroutines.launch

// [A] Module 2 - Job repository, now backed by Supabase.
// The PUBLIC API is the same as the old in-memory mock, so every
// ViewModel and screen above keeps working - that is the whole point
// of the Repository layer in UDF ("the single switch").
// Pattern: StateFlow cache + refresh() after writes + Realtime push.
object JobRepository {

    private const val TAG = "JobRepository"
    private val supabase get() = SupabaseClientProvider.client

    // Repository-owned background scope (repos outlive any single screen).
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    private val _jobs = MutableStateFlow<List<Job>>(emptyList())
    val jobs: StateFlow<List<Job>> = _jobs.asStateFlow()

    init {
        scope.launch { refresh() }
        scope.launch { subscribeToChanges() }
    }

    // Pull the current table into the cache. A failed read keeps the previous
    // cache on purpose - that is the graceful degradation for a list screen:
    // stale jobs beat an empty screen, and Realtime will catch us up. Writes
    // are different (see below): those the user must be told about.
    suspend fun refresh() {
        resultOf {
            supabase.from("jobs").select().decodeList<JobRow>()
        }.onSuccess { rows ->
            _jobs.value = rows.map { it.toDomain() }
        }.onFailure {
            Log.e(TAG, "Loading jobs failed (offline?)", it)
        }
    }

    fun getJobById(jobId: String): Flow<Job?> =
        jobs.map { list -> list.find { it.id == jobId } }

    // The three writes below used to swallow their failure and return Unit, so
    // "Publish Job" on a dead connection navigated back as if it had worked.
    // They now report an AppError and the screen shows a snackbar.
    suspend fun addJob(job: Job): Outcome<Unit> = write("Insert job failed") {
        supabase.from("jobs").insert(job.toInsert()) // id generated by DB
    }

    suspend fun updateJob(job: Job): Outcome<Unit> = write("Update job failed") {
        supabase.from("jobs").update(job.toInsert()) {
            filter { eq("id", job.id) }
        }
    }

    suspend fun deleteJob(jobId: String): Outcome<Unit> = write("Delete job failed") {
        supabase.from("jobs").delete {
            filter { eq("id", jobId) }
        }
    }

    // One write, one re-sync, one mapped error. Refresh runs either way: a
    // rejected write often means our cache is the stale thing.
    private suspend inline fun write(what: String, block: () -> Unit): Outcome<Unit> {
        val result = resultOf(block)
        refresh()
        return result.fold(
            onSuccess = { Ok },
            onFailure = { Outcome.Failure(it.logged(TAG, what)) },
        )
    }

    // Realtime: any change to the jobs table (from ANY device) re-syncs
    // the cache, so all screens update live without pull-to-refresh.
    private suspend fun subscribeToChanges() {
        resultOf {
            val channel = supabase.channel("public-jobs")
            channel.postgresChangeFlow<PostgresAction>(schema = "public") {
                table = "jobs"
            }.onEach { refresh() }.launchIn(scope)
            channel.subscribe()
        }.onFailure { Log.e(TAG, "Realtime subscribe failed", it) }
    }
}
